development:
  adapter: sqlite3
  database: db/development.db

production:
  adapter: postgresql
  host: 'ec2-107-20-159-103.compute-1.amazonaws.com'
  port: '5432'
  database: 'd32ger8skj457t'
  username: 'imoocnxjtelwlg'
  password: '2STVYB-H0X1xc-hhcCCgJynh4B'
